server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://localhost:8080
          predicates:
            - Path=/name/**

      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://8.134.133.xxx:8848
